apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: shoes-app-sa
      containers:
      - name: backend
        image: akhilsabbisetty/shoe-app:backend-latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shoes
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
