apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: shoes-app-sa
      containers:
      - name: backend
        image: akhilsabbisetty/shoe-app:backend-latest  # Use the actual Docker image pushed from CI
        ports:
        - containerPort: 8080
