apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: shoes-app-sa
      imagePullSecrets:
        - name: jfrog-docker-cred  # Replace if using private registry
      containers:
        - name: backend
          image: akhilsabbisetty/shoe-app:backend-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health  # adjust if your app exposes health on a different path
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
