apiVersion: v1
kind: ServiceAccount
metadata:
  name: shoes-app-sa
  namespace: shoes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shoes-app-role
  namespace: shoes
rules:
- apiGroups: [""]
  resources: ["pods","services","configmaps"]
  verbs: ["get","list","create","update","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shoes-app-rolebinding
  namespace: shoes
subjects:
- kind: ServiceAccount
  name: shoes-app-sa
  namespace: shoes
roleRef:
  kind: Role
  name: shoes-app-role
  apiGroup: rbac.authorization.k8s.io
