apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: shoes-app-sa
      containers:
      - name: backend
        image: <JFROG_HOST>/docker-local/shoes-backend:latest
        ports:
        - containerPort: 8080
